/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (storage, database, sources, queue) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Readiness"];
                    };
                };
                /** @description Not ready or draining */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Readiness"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus exposition format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with username and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Logged in; sets the `slc_session` cookie */
                200: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out (revokes the session) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, permissions and CSRF token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change own password (revokes other sessions) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        current_password: string;
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Password changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search logs (newest first, cursor pagination)
         * @description Requires `logs:search`; a `native` query additionally requires `logs:query_native`.
         *     When the native query contains pipes (`| stats …`), the response has
         *     `mode: table` with `columns`/`table_rows` instead of log rows.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SearchResponse"];
                    };
                };
                400: components["responses"]["Problem"];
                403: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
                504: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/histogram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log volume over time, optionally split by a field */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HistogramRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistogramResponse"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top values with exact counts for several fields */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FacetsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FacetsResponse"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aggregations (count, count_distinct, top) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatsResponse"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/tail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live tail (Server-Sent Events)
         * @description Requires `logs:tail`. Events:
         *
         *     - `logs` — `data: {"rows": [LogRow, …]}` (coalesced, at most every 250 ms or 500 rows)
         *     - `stats` — `data: {"rows_sent": n, "dropped_client_slow": n}`
         *     - `error` — `data: Problem`; the stream then ends
         *
         *     Comment lines (`: heartbeat`) are sent every 15 s.
         */
        get: {
            parameters: {
                query?: {
                    /** @description base64url (no padding) encoded JSON `TailQuery` */
                    q?: string;
                    /** @description How far back to start, e.g. `5s` (default) up to `1m`. */
                    start_offset?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                403: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Streamed export (CSV, NDJSON, JSON)
         * @description Requires `logs:export`. The body is streamed row by row. Browsers that
         *     cannot stream a fetch response to disk may submit an HTML form with
         *     `application/x-www-form-urlencoded` fields `request` (the JSON
         *     `ExportRequest`) and `csrf_token`.
         */
        post: {
            parameters: {
                query: {
                    format: "csv" | "ndjson" | "json";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExportRequest"];
                    "application/x-www-form-urlencoded": {
                        request?: string;
                        csrf_token?: string;
                    };
                };
            };
            responses: {
                /** @description Attachment */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        "X-Export-Limit"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                        "application/x-ndjson": string;
                        "application/json": string;
                    };
                };
                403: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a filter/native query and return the compiled native query */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filter?: components["schemas"]["FilterExpr"];
                        native?: components["schemas"]["NativeQuery"];
                    };
                };
            };
            responses: {
                /** @description Result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Field names present in the selection */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Selection"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top values of one field (exact counts) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    field: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FieldValuesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldValuesResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Overview tiles */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DashboardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardOverview"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log volume split by severity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DashboardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistogramResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Top values of a core field */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DashboardRequest"] & {
                        /** @enum {string} */
                        field: "hostname" | "app_name" | "source_ip" | "facility" | "severity" | "format" | "source";
                        /** @default 10 */
                        limit?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FieldValuesResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/ingestion-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingestion rates over time from node statistics (max 24 h) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DashboardRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestionRateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved searches visible to the user */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["SavedSearch"][];
                            next_cursor?: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a saved search */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavedSearchInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearch"];
                    };
                };
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-searches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a saved search */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearch"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        /** Update a saved search (optimistic concurrency via `version`) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavedSearchInput"] & {
                        version: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedSearch"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        post?: never;
        /** Delete a saved search */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys (own keys; all keys for admins) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ApiKey"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an API key (the secret is shown once) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        scopes: components["schemas"]["Permission"][];
                        /** Format: date-time */
                        expires_at?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key: components["schemas"]["ApiKey"];
                            /** @description Full key `slc_<id>_<secret>`; not retrievable later */
                            secret: string;
                        };
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest JSON logs
         * @description Requires an API key with `logs:ingest`. Accepts one JSON object, a JSON
         *     array of objects, or NDJSON (`application/x-ndjson`). `Content-Encoding:
         *     gzip` is supported. Invalid lines are reported; valid lines are accepted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never> | Record<string, never>[];
                    "application/x-ndjson": string;
                };
            };
            responses: {
                /** @description Accepted into the pipeline */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestResponse"];
                    };
                };
                401: components["responses"]["Problem"];
                413: components["responses"]["Problem"];
                /** @description Pipeline saturated; retry after the indicated delay. Partial results are reported. */
                503: {
                    headers: {
                        "Retry-After"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed health of this node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemHealth"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingestion counters and rates per source and node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemIngestion"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage backend, usage and retention */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemStorage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            request_id?: string;
            /**
             * @description Stable machine-readable code: bad_request, invalid_time_range, invalid_cursor,
             *     unauthenticated, session_expired, forbidden, csrf_failed, not_found, conflict,
             *     payload_too_large, unsupported_media_type, validation_failed, query_invalid,
             *     rate_limited, too_many_concurrent_queries, too_many_tail_sessions,
             *     ingest_backpressure, storage_unavailable, query_timeout, internal
             */
            code: string;
            errors?: {
                pointer?: string;
                position?: number;
                message?: string;
            }[];
        };
        /** @enum {string} */
        Permission: "dashboard:view" | "logs:search" | "logs:tail" | "logs:view_raw" | "logs:query_native" | "logs:export" | "logs:ingest" | "searches:read" | "searches:write" | "sources:read" | "sources:manage" | "system:view" | "config:view" | "config:manage" | "retention:manage" | "users:manage" | "apikeys:own" | "apikeys:manage" | "audit:view";
        /** @enum {string} */
        Role: "admin" | "operator" | "viewer";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name?: string;
            role: components["schemas"]["Role"];
            must_change_password: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at?: string | null;
        };
        Session: {
            user: components["schemas"]["User"];
            permissions: components["schemas"]["Permission"][];
            csrf_token: string;
        };
        Readiness: {
            /** @enum {string} */
            status: "ready" | "not_ready" | "draining";
            node?: string;
            version?: string;
            components: components["schemas"]["ComponentStatus"][];
        } & {
            [key: string]: unknown;
        };
        ComponentStatus: {
            name: string;
            /** @enum {string} */
            status: "ok" | "fail";
            error?: string;
        };
        TimeRange: {
            /**
             * @example now-1h
             * @example 2026-09-14T10:00:00Z
             */
            from: string;
            /** @example now */
            to: string;
            /**
             * @description IANA timezone for `/d` rounding and bucket alignment
             * @default UTC
             */
            tz?: string;
        };
        ResolvedRange: {
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string;
        };
        NativeQuery: {
            /** @constant */
            dialect: "logsql";
            text: string;
        };
        /** @description Backend-neutral filter AST (discriminated by `op`). */
        FilterExpr: components["schemas"]["BoolExpr"] | components["schemas"]["NotExpr"] | components["schemas"]["TextExpr"] | components["schemas"]["FieldValueExpr"] | components["schemas"]["FieldValuesExpr"] | components["schemas"]["FieldExistsExpr"];
        BoolExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "and" | "or";
            args: components["schemas"]["FilterExpr"][];
        };
        NotExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "not";
            arg: components["schemas"]["FilterExpr"];
        };
        TextExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "text";
            value: string;
        };
        FieldValueExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "eq" | "ne" | "contains" | "starts_with" | "regex" | "gt" | "gte" | "lt" | "lte" | "cidr";
            /** @description Storage field name; `message` and `timestamp` are aliases of `_msg`/`_time` */
            field: string;
            value: string;
        };
        FieldValuesExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "in" | "not_in";
            field: string;
            values: string[];
        };
        FieldExistsExpr: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "exists" | "not_exists";
            field: string;
        };
        Selection: {
            time_range: components["schemas"]["TimeRange"];
            filter?: components["schemas"]["FilterExpr"];
            native?: components["schemas"]["NativeQuery"];
        };
        SearchRequest: components["schemas"]["Selection"] & {
            /** @description Projection (storage field names); omit for all fields */
            fields?: string[];
            /** @default 200 */
            limit?: number;
            cursor?: string | null;
        };
        /**
         * @description A log record. Core fields are top level; dynamic fields are under
         *     `fields` and static labels under `labels` (both keyed by name without
         *     prefix). Absent values are omitted.
         */
        LogRow: {
            /** Format: date-time */
            timestamp: string;
            /** Format: date-time */
            received_at?: string;
            message?: string;
            hostname?: string;
            source_ip?: string;
            source_port?: number;
            peer_ip?: string;
            facility?: string;
            facility_code?: number;
            /** @enum {string} */
            severity?: "emergency" | "alert" | "critical" | "error" | "warning" | "notice" | "info" | "debug";
            severity_code?: number;
            priority?: number;
            protocol?: string;
            format?: string;
            app_name?: string;
            process_id?: string;
            message_id?: string;
            source?: string;
            source_type?: string;
            raw_message?: string;
            parse_error?: string;
            /** @enum {string} */
            time_source?: "received" | "adjusted";
            severity_source?: string;
            timestamp_raw?: string;
            truncated?: boolean;
            fields_dropped?: number;
            labels?: {
                [key: string]: string;
            };
            fields?: {
                [key: string]: string;
            };
            _ref: {
                stream_id: string;
                time_ns: string;
            };
        };
        SearchResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            /** @enum {string} */
            mode: "logs" | "table";
            rows?: components["schemas"]["LogRow"][];
            /** @description `table` mode only */
            columns?: string[];
            /** @description `table` mode only */
            table_rows?: {
                [key: string]: string;
            }[];
            page?: {
                returned: number;
                next_cursor?: string | null;
                tie_overflow: boolean;
            };
            /** @description The backend query that was executed (for display) */
            native_compiled?: string;
            stats: {
                duration_ms: number;
            };
        };
        HistogramRequest: components["schemas"]["Selection"] & {
            /** @description Field to split buckets by (e.g. severity) */
            split_by?: string | null;
            /**
             * @description Target maximum number of buckets
             * @default 120
             */
            buckets?: number;
            /** @default 8 */
            split_limit?: number;
        };
        HistogramResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            /** @example 15m */
            step: string;
            step_seconds: number;
            total: number;
            split_by?: string | null;
            /** @description Split values ordered by total count */
            split_values?: string[];
            /** @description Values beyond split_limit were merged into `other` */
            split_other?: boolean;
            buckets: {
                /** Format: date-time */
                t: string;
                total: number;
                split?: {
                    [key: string]: number;
                };
            }[];
        };
        FacetsRequest: components["schemas"]["Selection"] & {
            fields: string[];
            /** @default 10 */
            limit_per_field?: number;
        };
        ValueCount: {
            value: string;
            count: number;
        };
        FacetsResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            facets: {
                field: string;
                values: components["schemas"]["ValueCount"][];
            }[];
        };
        StatsRequest: components["schemas"]["Selection"] & {
            aggregations: {
                /** @enum {string} */
                type: "count" | "count_distinct" | "top";
                field?: string;
                /** @default 10 */
                limit?: number;
            }[];
        };
        StatsResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            results: {
                type: string;
                field?: string;
                /** @description count / count_distinct */
                value?: number;
                /** @description top */
                values?: components["schemas"]["ValueCount"][];
            }[];
        };
        TailQuery: {
            filter?: components["schemas"]["FilterExpr"];
            native?: components["schemas"]["NativeQuery"];
        };
        ExportRequest: components["schemas"]["Selection"] & {
            /** @description Required for CSV; defaults to core fields */
            fields?: string[];
            /** @default 100000 */
            limit?: number;
        };
        ValidateResponse: {
            valid: boolean;
            native_compiled?: string;
            errors?: {
                message?: string;
                position?: number;
                pointer?: string;
            }[];
        };
        FieldInfo: {
            name: string;
            count?: number;
            count_approximate?: boolean;
            /** @enum {string} */
            kind: "core" | "label" | "dynamic";
        };
        FieldsResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            fields: components["schemas"]["FieldInfo"][];
        };
        FieldValuesRequest: components["schemas"]["Selection"] & {
            /** @description Case-insensitive substring filter */
            search?: string;
            /** @default 20 */
            limit?: number;
        };
        FieldValuesResponse: {
            resolved_range?: components["schemas"]["ResolvedRange"];
            field: string;
            values: components["schemas"]["ValueCount"][];
        };
        DashboardRequest: {
            time_range: components["schemas"]["TimeRange"];
        };
        DashboardOverview: {
            resolved_range: components["schemas"]["ResolvedRange"];
            logs_in_range: number;
            logs_today: number;
            /** @description severity_code <= 3 */
            errors_in_range: number;
            /** @description Distinct hostnames in range */
            active_sources: number;
            storage?: components["schemas"]["StorageUsage"];
            ingest_rate?: {
                logs_per_second?: number;
                bytes_per_second?: number;
                window_seconds?: number;
            };
            /** Format: date-time */
            cached_at?: string;
        };
        IngestionRateResponse: {
            resolved_range: components["schemas"]["ResolvedRange"];
            step_seconds?: number;
            series: {
                /** Format: date-time */
                t: string;
                received_per_second?: number;
                stored_per_second?: number;
                dropped_per_second?: number;
                parse_errors_per_second?: number;
            }[];
        };
        SavedSearchQuery: {
            filter?: components["schemas"]["FilterExpr"];
            native?: components["schemas"]["NativeQuery"];
        };
        SavedSearchInput: {
            name: string;
            description?: string;
            query: components["schemas"]["SavedSearchQuery"];
            columns?: string[];
            default_time_range?: components["schemas"]["TimeRange"];
            /**
             * @default private
             * @enum {string}
             */
            visibility?: "private" | "shared";
        };
        SavedSearch: components["schemas"]["SavedSearchInput"] & {
            /** Format: uuid */
            id: string;
            /** @description Set when `query.native` is present */
            dialect?: string | null;
            created_by: {
                /** Format: uuid */
                id: string;
                username: string;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        ApiKey: {
            /** Format: uuid */
            id: string;
            key_id: string;
            name: string;
            scopes: components["schemas"]["Permission"][];
            owner?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        IngestResponse: {
            accepted: number;
            rejected: number;
            errors?: {
                line?: number;
                error?: string;
            }[];
        };
        SourceStatus: {
            name: string;
            type: string;
            protocol?: string;
            address?: string;
            /** @enum {string} */
            state: "running" | "stopped" | "error" | "disabled";
            error?: string;
            /** Format: date-time */
            since?: string;
        };
        SystemHealth: {
            /** @enum {string} */
            status: "ready" | "not_ready" | "draining";
            node: string;
            version: string;
            roles?: string[];
            uptime_seconds: number;
            components: components["schemas"]["ComponentStatus"][];
            sources?: components["schemas"]["SourceStatus"][];
        };
        SourceCounters: {
            name: string;
            protocol?: string;
            state?: string;
            received?: number;
            parsed?: number;
            parse_errors?: number;
            stored?: number;
            dropped?: {
                [key: string]: number;
            };
            active_connections?: number;
            received_per_second?: number;
            stored_per_second?: number;
        };
        SystemIngestion: {
            node: string;
            sources: components["schemas"]["SourceCounters"][];
            queue: {
                messages?: number;
                bytes?: number;
                capacity_messages?: number;
                capacity_bytes?: number;
            };
            storage_healthy?: boolean;
            e2e_latency_p50_seconds?: number | null;
            e2e_latency_p99_seconds?: number | null;
        };
        StorageUsage: {
            compressed_bytes?: number;
            uncompressed_bytes?: number;
            free_disk_bytes?: number;
            total_disk_bytes?: number;
        };
        SystemStorage: {
            backend: string;
            reachable: boolean;
            capabilities?: {
                native_dialects?: string[];
                native_tail?: boolean;
                per_tenant_retention?: boolean;
            };
            usage?: components["schemas"]["StorageUsage"];
            retention?: {
                configured?: string;
                backend?: string;
                /** @enum {string} */
                status?: "in_sync" | "drift" | "unknown";
            };
        };
    };
    responses: {
        /** @description Problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
